apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hackathon-ingress
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /$2  # This will rewrite the path
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ deployment.host }}
      secretName: main-tls
  rules:
    - host: {{ deployment.host }}
      http:
        paths:
          - path: /authentication(/|$)(.*)  # Matches /authentication followed by anything
            pathType: Prefix
            backend:
              service:
                name: hackathonauthservice
                port:
                  number: 8100
          - path: /main(/|$)(.*)  # Matches everything else
            pathType: Prefix
            backend:
              service:
                name: hackathongateway  # Added gateway service
                port:
                  number: {{ deployment.port }}  